### ISSUE TITLE
Return unmasked value by default

### ISSUE THREAD

**Issue by bobyenser** [raphadesa/BlazorInputMask#11]
Hi,

I have a situation where my phone number is stored in the database unmasked (i.e 1234567890).  I bind that value to InputMask and it is displayed correctly as 123-456-7890.  I'd like the unmasked value to be returned from the 2 way binding instead of having to get it from rawValue.  Is that possible?  Other masked controls I've used work this way.

Thanks,
Bob

**Comment by raphadesa** [comment]
Hello,

Sorry to reply only now, could you tell me what you are trying to achieve so I can help you ? 

Thank you,

Raphaël

**Comment by bobyenser** [comment]
Sure.  I have a use case where I need to display a phone number masked, 123-456-7890.  But the value stored in the database is unmasked, 1234567890.  Other use cases call for the value to be stored masked.  Below is the javascript and blazor component I used to achieve this.  I'm not sure if this is the best solution, but it works.

//mask javascript code
window.mask = (id, mask, isRegEx, dotnetHelper, returnMaskedValue) => {
    var pattern;
    if (isRegEx)
        pattern = new RegExp(mask);
    else
        pattern = mask;
    var customMask = IMask(
        document.getElementById(id), {
            mask: pattern, 
            lazy: false, //this will show the placholder all the time
            commit: function (value, masked) {
                if (returnMaskedValue === true) {
                    dotnetHelper.invokeMethodAsync('returnValue', value);
                } else {
                    dotnetHelper.invokeMethodAsync('returnValue', this.unmaskedValue);
                }
            }
    });
};


//blazor component
@inject IJSRuntime JSRuntime
@inherits InputBase<string>

@if (validateOnKeyPress)
{
    <input id="@id" @attributes="AdditionalAttributes" class="@CssClass" value="@CurrentValue" @oninput="EventCallback.Factory.CreateBinder<string>(this, __value => CurrentValueAsString = __value, CurrentValueAsString)" />
}
else
{
    <input id="@id" @attributes="AdditionalAttributes" class="@CssClass" @bind="CurrentValueAsString" />
}

@code {
    [Parameter]
    public string id { get; set; } = Guid.NewGuid().ToString();
    [Parameter]
    public bool validateOnKeyPress { get; set; } = true;
    [Parameter]
    public bool useMaskedValue { get; set; } = true;

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            var pattern = AdditionalAttributes["data-mask"].ToString();
            var isRegEx = pattern.StartsWith("/") && pattern.EndsWith("/");
            if (isRegEx)
                pattern = pattern.TrimStart('/').TrimEnd('/');
            await JSRuntime.InvokeVoidAsync("mask", id, pattern, isRegEx, DotNetObjectReference.Create(this), useMaskedValue);
        }
    }
    protected override bool TryParseValueFromString(string value, out string result, out string validationErrorMessage)
    {
        result = value;
        validationErrorMessage = null;
        return true;
    }

    [JSInvokable]
    public void returnValue(string value)
    {
        CurrentValueAsString = value;
    }
}

**Comment by raphadesa** [comment]
Hello,

I don’t see the point why you’re using code to get the masked content, as it’s already available on the model the mask is bound to. If you need the raw value you can either use the function I wrote or perform a replace. I don’t see either the reason why you need two-way binding.

Regards,

Raphaël
________________________________
De : bobyenser ***@***.***>
Envoyé : Thursday, September 2, 2021 7:41:17 PM
À : raphadesa/BlazorInputMask ***@***.***>
Cc : Raphaël Desalbres ***@***.***>; Comment ***@***.***>
Objet : Re: [raphadesa/BlazorInputMask] Return unmasked value by default (#11)


Sure. I have a use case where I need to display a phone number masked, 123-456-7890. But the value stored in the database is unmasked, 1234567890. Other use cases call for the value to be stored masked. Below is the javascript and blazor component I used to achieve this. I'm not sure if this is the best solution, but it works.

//mask javascript code
window.mask = (id, mask, isRegEx, dotnetHelper, returnMaskedValue) => {
var pattern;
if (isRegEx)
pattern = new RegExp(mask);
else
pattern = mask;
var customMask = IMask(
document.getElementById(id), {
mask: pattern,
lazy: false, //this will show the placholder all the time
commit: function (value, masked) {
if (returnMaskedValue === true) {
dotnetHelper.invokeMethodAsync('returnValue', value);
} else {
dotnetHelper.invokeMethodAsync('returnValue', this.unmaskedValue);
}
}
});
};

//blazor component
@Inject<https://github.com/Inject> IJSRuntime JSRuntime
@inherits<https://github.com/inherits> InputBase

@if<https://github.com/if> (validateOnKeyPress)
{
<input ***@***.***<https://github.com/id>" @attributes="AdditionalAttributes" ***@***.***" ***@***.***<https://github.com/CurrentValue>" @oninput="EventCallback.Factory.CreateBinder(this, __value => CurrentValueAsString = __value, CurrentValueAsString)" />
}
else
{
<input ***@***.***<https://github.com/id>" @attributes="AdditionalAttributes" ***@***.***" @Bind<https://github.com/Bind>="CurrentValueAsString" />
}

@code<https://github.com/code> {
[Parameter]
public string id { get; set; } = Guid.NewGuid().ToString();
[Parameter]
public bool validateOnKeyPress { get; set; } = true;
[Parameter]
public bool useMaskedValue { get; set; } = true;

protected override async Task OnAfterRenderAsync(bool firstRender)
{
    if (firstRender)
    {
        var pattern = AdditionalAttributes["data-mask"].ToString();
        var isRegEx = pattern.StartsWith("/") && pattern.EndsWith("/");
        if (isRegEx)
            pattern = pattern.TrimStart('/').TrimEnd('/');
        await JSRuntime.InvokeVoidAsync("mask", id, pattern, isRegEx, DotNetObjectReference.Create(this), useMaskedValue);
    }
}
protected override bool TryParseValueFromString(string value, out string result, out string validationErrorMessage)
{
    result = value;
    validationErrorMessage = null;
    return true;
}

[JSInvokable]
public void returnValue(string value)
{
    CurrentValueAsString = value;
}


}

**Comment by bobyenser** [comment]
It's much cleaner to get the raw value through the binding, rather than use
the function to get it and update my model.  Based on that new parameter,
the model will automatically be updated with either the masked or raw value.

It eliminates the need to ref the mask and manually update the model.  The
2 lines below from your Index.razor aren't needed anymore.

InputMask mask { get; set; }
var rawValue = mask.rawValue;

**Comment by raphadesa** [comment]
Ok I got it, thanks for your contribution, can I use your code for the next version? I can mention your name on the credits.

Best regards,

Raphaël

**Comment by bobyenser** [comment]
You certainly can.  Thanks!

**Comment by PibePlayer** [comment]
I would like this to be included :)

**Comment by raphadesa** [comment]
Hello, I've finally added a new parameter, "returnRawValue", which is true by default. I've also updated the nuget package. Thanks @bobyenser !!!
