### ISSUE TITLE
RegEx does not work

### ISSUE THREAD

**Issue by marciusnery** [raphadesa/BlazorInputMask#12]
Hi.

I'm try to use a RegEx and does not work.

My regex:
data-mask="/^\([1-9]{2}\) (?:[2-8]|9[1-9])[0-9]{3}\-[0-9]{4}$/"

**Comment by raphadesa** [comment]
Hello, please check if you regex works here : http://jsfiddle.net/4jeUr/

Regards,

Raphaël

**Comment by Aidan-Paetsch** [comment]
I too am having this issue with valid regex: /^(1 )?\((?:[2-9][0-9])[0-9]\) [0-9]{3}-[0-9]{4}$/
It does not appear that regex is actually supported as the component will not accept any form of valid regex that I pass to it.
