### ISSUE TITLE
Value is being cached

### ISSUE THREAD

**Issue by mongezisithole** [raphadesa/BlazorInputMask#13]
Hi,

I have a strange problem, I'm not sure if it is my code or what but whenever I try to clear the value of the inputMask it always returns the old value. I clear it by setting the property bound to it to null, it does clears the input but as soon as I enter a new value the old one comes back. I hope I make sense.

**Comment by raphadesa** [comment]
Hello,

Could you send me a code exerpt you used to achieve this ? You should reset the underlying model by setting it to either null or string.Empty...

**Comment by mongezisithole** [comment]
This is how we define the control
![image](https://user-images.githubusercontent.com/44968796/153856536-dfad54e0-4ad6-46fa-bca7-e3cc1af09845.png)

This is the ValueChanged()
![image](https://user-images.githubusercontent.com/44968796/153856711-4c5e4af5-a9fa-49b0-af42-d4cbd4a47339.png)

And this is how we set the model to empty strings.
![image](https://user-images.githubusercontent.com/44968796/153857106-9660055c-be82-4e01-9302-0ddb61da725a.png)

Do you think changing it to string.Empty would make a difference instead of using " "?

**Comment by raphadesa** [comment]
Hello,

Why don't you use an InputForm with an EditContext like this sample: https://github.com/raphadesa/BlazorInputMask/blob/master/BlazorInputMask/Pages/Index2.razor  ? 
I haven't tested the component with your approach.

**Comment by mongezisithole** [comment]
Hi,

Even if I do it that way I still get the same issue, it's like the value is being cached somewhere for few minutes. Maybe the problem is with my code. 

Thanks,

**Comment by mongezisithole** [comment]
Hi,

I have made few changes to you code, now everything is working. Do you mind if I push my changes?

**Comment by raphadesa** [comment]
Hello, yes, please do !
