### ISSUE TITLE
Incorrect docs or filename for js resources

### ISSUE THREAD

**Issue by aterbo** [raphadesa/BlazorInputMask#14]
Hello,

The readme references adding the js files with the following lines:

```
<script type="text/javascript" src="_content/BlazorInputMask/Main.js"></script>
<script type="text/javascript" src="_content/BlazorInputMask/IMask.js"></script>
```

Note that `Main.js` is capitalized. The actual file in the repo is lowercase -- `main.js`. This isn't a problem on most builds or deployments, but I recently deployed this library into a Linux Docker container, and due to the mismatch in case I was getting a 404 error where it couldn't find main.js. 

I'm happy to submit a PR to fix the issue, but would you prefer to make the js files and documents consistently capitalized `Main.js and IMask.js` or lowercase `main.js and imask.js`?

Thanks!

**Comment by raphadesa** [comment]
Hello, 

Please feel free to change the component the way you want, it's a MIT licence !

**Comment by raphadesa** [comment]
Sure, It's done with the package upgrade to .NET 7 !
