### ISSUE TITLE
Element value was changed outside of mask

### ISSUE THREAD

**Issue by andrewtsybulia** [raphadesa/BlazorInputMask#16]
Hello, I've been using your library for more than a year and now I am faced with a problem. Below I attached a screen with a little sample:
![image](https://user-images.githubusercontent.com/53795395/210092436-00565984-855e-4cce-b9c3-d1056bb1f4b0.png)
1) So in the beginning I have this value, real one: 1111 and masked 11.11:
![image](https://user-images.githubusercontent.com/53795395/210092453-dcf6aff3-d7f3-4c7d-a8bf-31bfe4c056a9.png)
2) Then I switch the active user to the second one by pressing on ActiveUser(2). 
![image](https://user-images.githubusercontent.com/53795395/210093387-2544cf6f-39d6-4add-952a-22fd5d8f7879.png)
3) First of all the input now is 2222, it's not masked. And I want to add for example 9, I click on the input and I have a warning message in the console:
![image](https://user-images.githubusercontent.com/53795395/210092601-c5d5cc81-11a2-47ed-b78f-a558eaefe727.png)
4) Then I add the number 9(**without removing focus from the input**)
![image](https://user-images.githubusercontent.com/53795395/210093175-c5095cbf-5ad9-420b-b191-ec547e296eb0.png)
5) The number 1 that has been added it's a number from the previous input value.

So, I think it is because the InputMask component in my case is rendered only once:
![image](https://user-images.githubusercontent.com/53795395/210093777-b137fa7f-d8d0-45cc-ad94-5d46077f17cf.png)
Only when it is the first render.

Any thoughts? :)

**Comment by raphadesa** [comment]
Hello,

Here is a working solution for your problem !

@page "/"
@using BlazorInputMask

<EditForm Model="_users">
    @foreach (var item in _users)
    {        
        <div class="form-group">
            <InputMask id=@item.Id.ToString() @bind-Value=@item.Amount data-mask="00.00.00.00.00" placeholder="phone no" style="@(item.isVisible ? "display:block":"display:none")" />   
        </div>
        
    }
  </EditForm>


<button class="btn btn-primary" @onclick=@(() => ActiveUser(1))>ActiveUser(1)</button>
<button class="btn btn-primary" @onclick=@(() => ActiveUser(2))>ActiveUser(2)</button>
<button class="btn btn-primary" @onclick=@(() => ActiveUser(3))>ActiveUser(3))</button>

@code
{
    private readonly List<User> _users = new()
{
new() { Id = 1, Amount = "1111"},
new() { Id = 2, Amount= "2222"},
new() { Id = 3, Amount = "3333"}
};


    private int _activeUserId = 1;

    protected override void OnInitialized()
    {
        _users.First().isVisible = true;
        base.OnInitialized();    
    }

    private void ActiveUser(int id)
    {
        _users.ForEach(c => c.isVisible = false);
        _users.First(c => c.Id == id).isVisible =true;
    }
}

**Comment by raphadesa** [comment]
Hello,

Here's a working solution for your problem !

![image](https://user-images.githubusercontent.com/3438864/210441491-0eeca7a1-af02-4f6d-be25-8936f0cd2594.png)

**Comment by andrewtsybulia** [comment]
Ye, it is a kinda fix but it has decreased performance. In my case, I have many "users" and every user has many "inputs" ;(

**Comment by raphadesa** [comment]
Hello,

Could you give me more details of what you are trying to achieve?

Regards,

Raphael

**Comment by raphadesa** [comment]
Hello, I finally solved your problem ! Just add a @key to the InputMask and it should work like a charm !!!

  <InputMask @key=@item.Id id=@item.Id.ToString()

**Comment by andrewtsybulia** [comment]
> Hello, I finally solved your problem ! Just add a @key to the InputMask and it should work like a charm !!!
> 
> <InputMask @key=@item.Id id=@item.Id.ToString()

Gonna try it, thank you
