### ISSUE TITLE
Changing the mask dynamically?

### ISSUE THREAD

**Issue by dhanlon2** [raphadesa/BlazorInputMask#17]
I have a form where the mask for some fields might vary based on the current value of another form field. Basically I'm trying to have country specific masks for things like area code, phone number, ssn etc, and country is an editable field.

<InputMask @bind-Value="M[fld.Name]!.StringValue" data-mask="@M.Masks[fld.Name]" />

I've verified that the mask values are updating correctly, but they are not being applied. I think the mask is applied only on first render of the component?

Can there be a parameter to change that behaviour, or is there some other issue that would prevent it working?

**Comment by raphadesa** [comment]
Hello, you can try by putting a @key value directive to the input Mask. If it still doesn't work maybe you can send some more code ?

**Comment by raphadesa** [comment]
Hello,

Sorry for the late reply ! 

I have added a function updateMask (also in latest nuget), please see here for details: 

https://github.com/raphadesa/BlazorInputMask/blob/master/BlazorInputMask/Pages/Index3.razor

**Comment by dhanlon2** [comment]
Thanks, I will have a look at it. But it looks like, to update the input mask, I need a have a reference to the inputmask component.

This may be my lack of experience with Blazor, but I'm finding it very awkward to work with component references. The content of my component is built dynamically from backend parameters. Usually to obtain a component reference you declare a settable property in your component and use the @ref attribute to target that property. But I don't statically know what instances of inputmask I will have.

I already ran into this problem because I am interested in the raw input value which I can only get via the inputmask reference.

**Comment by raphadesa** [comment]
Hello, you're absolutely right ! 

Based on your feedback I've implemented an event OnChange,  which returns both the value and the mask raw value.

See here for more  details: https://github.com/raphadesa/BlazorInputMask/blob/master/BlazorInputMask/Pages/Index.razor
