### ISSUE TITLE
Using multiple InputMasks on a same page, only the last one works

### ISSUE THREAD

**Issue by Germandf** [raphadesa/BlazorInputMask#18]
Hi.

This behavior started from `v1.0.16`. Rolling back to `v1.0.15` fixes it.

If I use two or more input mask on the same page, only the last one works as expected. Taking this minimal working example:

``` razor
<InputMask id="id1" data-mask="00000000" validateOnKeyPress="false" @bind-Value="_someModel.Field1"/>
<InputMask id="id2" data-mask="00000000" validateOnKeyPress="false" @bind-Value="_someModel.Field2"/>
```

``` csharp
public partial class SomePage : ComponentBase
{
    private SomeModel _someModel = new();
}


public class SomeModel
{
    public string Field1 { get; set; } = "";
    public string Field2 { get; set; } = "";
}
```

The InputMask with id1 doesn't respect the mask, I can input letters, more than 8 characters length, etc.

Using only one InputMask also works just fine.

**Comment by raphadesa** [comment]
Hello, I apologize for the inconvenience, a new nuget package has just been published...
