### ISSUE TITLE
Bind on unmasked value

### ISSUE THREAD

**Issue by MAndrade1980** [raphadesa/BlazorInputMask#2]
Hi, is it possible to bind the component to the unmasked version of the inputted data? Currently it is binding the masked data.

**Comment by raphadesa** [comment]
Hello,

I'm afraid this is the default behavior of iMask component, to get unmasked data, you should replace masked values with additional code.

I'm sure that if I had made an unmasked data version, people would have asked: can I get masked data ?

Anyway, thanks for your input !

Raphaël...

Btw, what is you exact need for this component ?

**Comment by MAndrade1980** [comment]
We just wanted clean data saved, in our case for phone numbers we are binding to a property and having to remove parentheses, spaces, and dashes before saving numerics only. Would have been nice to have the numbers only being bound. Currently we are only using it for just that.

**Comment by raphadesa** [comment]
Hello, I have updated the demo site + the nuget package, with a feature to get the unmasked content.

To do so, please follow these steps:

1) Add a ref to the component

 <InputMask @ref="mask" id="yourId" @bind-Value= ... data-mask=...  />

2) On your code you set the object:
  InputMask mask { get; set; }

3) On the OnValidSubmit handler you can retrieve the mask.rawValue string data.

More info here: https://github.com/raphadesa/BlazorInputMask/blob/master/BlazorInputMask/Pages/Index.razor

Hope this helps !

Raphaël
