### ISSUE TITLE
Regex fail

### ISSUE THREAD

**Issue by RNovachkov** [raphadesa/BlazorInputMask#20]
It is not working with this Regex: `/^08[7-9]{1}\d{7}$|^09[8-9]{1}\d{7}$/`

**Comment by raphadesa** [comment]
Hello,

Sorry for the late reply...

Can you test your regex here, as I wasn't able to get it work...

https://jsfiddle.net/nz5376ag/

Regards,

Raphaël

**Comment by RNovachkov** [comment]
Hello,

I've tested it, and it's not working. But I saw where the problem is.

In: "[https://imask.js.org/guide.html#masked-base](https://imask.js.org/guide.html#masked-base)"
Search for: "Also make sure that mask or validator works with any of intermediate states, not just final value. For example to restrict input to "123" you do:"
![image](https://github.com/raphadesa/BlazorInputMask/assets/28736050/b8088c05-a633-41aa-bc22-36c9f0ff4031)


Regards:

Rumen
