### ISSUE TITLE
Does not work if I place multiple inputmasks on the same form/page

### ISSUE THREAD

**Issue by umahanov** [raphadesa/BlazorInputMask#21]
```
<div class="input-item">
<label for="firstname" class="input-label">Name</label>
<InputMask @ref="firstNameMask" id="firstname" @bind-Value="model.Name" class="input" data-mask="/^[\u0401\u0451\u0410-\u044f]+$/" placeholder="Input name"/>
<ValidationMessage For="@(() => model.Name)"/>
</div> <!-- input-item -->

<div class="input-item">
<label for="lastname" class="input-label">Lastname</label>
<InputMask @ref="lastNameMask" id="lastname" @bind-Value="model.Lastname" class="input" data-mask="/^[\u0401\u0451\u0410-\u044f]+$/" placeholder="Input lastnam"/>
<ValidationMessage For="@(() => model.Lastname)"/>
</div> <!-- input-item -->


@code {
	InputMask lastNameMask { get; set; }
	InputMask firstNameMask { get; set; }
}
```

As I understand, the problem is related to js. On first render the next script is executed twice, which leads my mask to work only on the second input. The first is replaced with second. 

```

var customMask = null;

window.mask = (id, mask, isRegEx, returnRawValue, dotnetHelper) => {    
    var pattern;    
    if (isRegEx)
        pattern = new RegExp(mask);
    else
        pattern = mask;
    if (customMask != null) {
        customMask.destroy();
    }    
    customMask = IMask(
        document.getElementById(id), {
        mask: pattern,
            commit: function (value, masked) {
                if (returnRawValue===true)                    
                    dotnetHelper.invokeMethodAsync('returnCurrentValue', this.unmaskedValue);
                else
                    dotnetHelper.invokeMethodAsync('returnCurrentValue', value);
                    
            }
    });
};

```

**Comment by raphadesa** [comment]
Hello,

Please use the latest version of my code or comment out the javascript part that destroys the component.

Regards,

Raphael
________________________________
De : umahanov ***@***.***>
Envoyé : Friday, April 14, 2023 7:04:19 PM
À : raphadesa/BlazorInputMask ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [raphadesa/BlazorInputMask] Does not work if I place multiple inputmasks on the same form/page (Issue #21)


                                                        <div class="input-item">
                                                                <label for="firstname" class="input-label">Name</label>
                                                                <InputMask @ref="firstNameMask" id="firstname" @bind-Value="model.Name" class="input" data-mask="/^[\u0401\u0451\u0410-\u044f]+$/" placeholder="Input name"/>
                                                                <ValidationMessage For="@(() => model.Name)"/>
                                                        </div> 

                                                        <div class="input-item">
                                                                <label for="lastname" class="input-label">Lastname</label>
                                                                <InputMask @ref="lastNameMask" id="lastname" @bind-Value="model.Lastname" class="input" data-mask="/^[\u0401\u0451\u0410-\u044f]+$/" placeholder="Input lastnam"/>
                                                                <ValidationMessage For="@(() => model.Lastname)"/>
                                                        </div> 


@code {
        InputMask lastNameMask { get; set; }
        InputMask firstNameMask { get; set; }
}


As I understand, the problem is related to js. On first render the next script is executed twice, which leads my mask to work only on the second input. The first is replaced with second.


var customMask = null;

window.mask = (id, mask, isRegEx, returnRawValue, dotnetHelper) => {
    var pattern;
    if (isRegEx)
        pattern = new RegExp(mask);
    else
        pattern = mask;
    if (customMask != null) {
        customMask.destroy();
    }
    customMask = IMask(
        document.getElementById(id), {
        mask: pattern,
            commit: function (value, masked) {
                if (returnRawValue===true)
                    dotnetHelper.invokeMethodAsync('returnCurrentValue', this.unmaskedValue);
                else
                    dotnetHelper.invokeMethodAsync('returnCurrentValue', value);

            }
    });
};
