### ISSUE TITLE
InputMask label not recognized

### ISSUE THREAD

**Issue by ShiruJan** [raphadesa/BlazorInputMask#22]
I want to test the InputMask in my Blazor app (Server Side). I installed the library through Nuget (version 1.0.20). I added the main.js and imask.js script references. Using the InputMask tag is not recognized on the page. I checked if it detects the namespace, but it doesn't. Am I missing some configuration? Greetings.

**Comment by raphadesa** [comment]
Hello, can you post some sample code ?

Regards,

Raphaël
