### ISSUE TITLE
Bug if you want to use scripts with clear button.

### ISSUE THREAD

**Issue by ru-talion** [raphadesa/BlazorInputMask#23]
Hello. Using this with a clear button then I see strange behavior.

![image](https://github.com/raphadesa/BlazorInputMask/assets/98240173/377bda74-a243-43e2-94cb-ea0e0a97fb85)

Scenario:
1) I enter 1111111111
2) I clean it using the button.
3) I enter 22222222
4) I see that the script added 1 to the end. This is mistake. I only drove 22222222.

![chrome_sJyN34y2wZ](https://github.com/raphadesa/BlazorInputMask/assets/98240173/db616a33-34a4-4974-9991-20e4690a19d9)

It remembers the last successful character and inserts it the second time you enter it.

How can I fix this? Thank you!

**Comment by ru-talion** [comment]
Sorry, I saw the answer in closed. =)

**Comment by raphadesa** [comment]
Hello ru-talion, I've created a new function clearValue();
On your sample please use:

async Task Clear()
 {
   await inputMask.clearValue();
   StateHasChanged();
 }

Please update the nuget package.

Regards,

Raphaël

**Comment by ru-talion** [comment]
Thank you so much for such a quick response! Everything works perfectly!

Please note this:
![image](https://github.com/raphadesa/BlazorInputMask/assets/98240173/2053ebd2-c064-4226-9fc0-fbe06ac45df0)

**Comment by ru-talion** [comment]
If there are several fields:
![image](https://github.com/raphadesa/BlazorInputMask/assets/98240173/7d265da2-7809-4cf4-aebd-022ae8deeac4)

New function clearValue(); works only on the last field:
![chrome_hUwNH2bj8S](https://github.com/raphadesa/BlazorInputMask/assets/98240173/82bd2787-ea17-4d33-a019-64adbc561a16)

**Comment by raphadesa** [comment]
Hello, I've fixed the bug, please update your solution to the latest nuget package !

**Comment by ru-talion** [comment]
Hello! When using the "clear" button, the mask does not allow you to enter the last 1 character. =((

![chrome_H9uvlpsBh4](https://github.com/raphadesa/BlazorInputMask/assets/98240173/c61697c7-de3e-4982-ac3b-31bd97b9d430)

**Comment by ru-talion** [comment]
Maybe it’s worth writing down masks in a dictionary? Take them from the dictionary and clear them?

![image](https://github.com/raphadesa/BlazorInputMask/assets/98240173/77d28b4d-c7a3-401b-832f-8a8880c24a63)

**Comment by ru-talion** [comment]
Watch this. It works! =))

![image](https://github.com/raphadesa/BlazorInputMask/assets/98240173/00bbe7e6-5f16-4ec0-8958-6834097d3b54)

**Comment by raphadesa** [comment]
Hello, many thanks for your solution, please update the Nuget Package !

**Comment by ru-talion** [comment]
You're welcome!
