### ISSUE TITLE
IMask {} properties such as Number, scale, radix etc?

### ISSUE THREAD

**Issue by iancoetzer** [raphadesa/BlazorInputMask#25]
How can I setup my mask using all these properties -  via a reference to the BlazorInputMask?

        var decimalMask1 = IMask(
            document.getElementById('idMask'), {
            mask: Number, 
            // other options are optional with defaults below
            scale: 2,  // digits after point, 0 for integers
            thousandsSeparator: ',',  // any single char
            padFractionalZeros: false,  // if true, then pads zeros at end to the length of scale
            normalizeZeros: true,  // appends or removes zeros at ends
            radix: '.',  // fractional delimiter
            mapToRadix: ['.'],  // symbols to process as radix

            // additional number interval options (e.g.)
            min: -10000,
            max: 10000        
        });

**Comment by raphadesa** [comment]
Hello, sorry for the late reply but I have no plans for such a feature in the near future...
