### ISSUE TITLE
Reverse mask for numbers

### ISSUE THREAD

**Issue by caio-delgado** [raphadesa/BlazorInputMask#26]
Is it possible to reverse the filling of the input mask for numbers, like currency?

Example: 0,00 mask:
Input 1 results in 0,01
Input 1234 results in 12,34
Input 12 results in 0,12

**Comment by raphadesa** [comment]
Hello,

In order to help you could you please tell me what you are trying to achieve ?

Thanks Raphael
________________________________
De : caio-delgado ***@***.***>
Envoyé : Friday, December 8, 2023 6:14:08 PM
À : raphadesa/BlazorInputMask ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [raphadesa/BlazorInputMask] Reverse mask for numbers (Issue #26)


Is it possible to reverse the filling of the input mask for numbers, like currency?

Example: 0,00 mask:
Input 1 results in 0,01
Input 1234 results in 12,34
Input 12 results in 0,12

**Comment by caio-delgado** [comment]
Hello,Sure. I have 2 situationls where I want to fill the input mask from right to left. Decimal values. The mask is 0,00 (comma is a decimal separator). Inputing data should yield:Input 1 = masked 0,01Input 123 = masked 1,23Input 1234 = masked 12,34I’d like it to fill from the right first and as numbers are inserted shift the rest left CaioEm 8 de dez. de 2023, à(s) 14:40, Raphaël Desalbres ***@***.***> escreveu:﻿
Hello,



In order to help you could you please tell me what you are trying to achieve ?



Thanks Raphael

________________________________

De : caio-delgado ***@***.***>

Envoyé : Friday, December 8, 2023 6:14:08 PM

À : raphadesa/BlazorInputMask ***@***.***>

Cc : Subscribed ***@***.***>

Objet : [raphadesa/BlazorInputMask] Reverse mask for numbers (Issue #26)





Is it possible to reverse the filling of the input mask for numbers, like currency?



Example: 0,00 mask:

Input 1 results in 0,01

Input 1234 results in 12,34

Input 12 results in 0,12

**Comment by raphadesa** [comment]
Hello Caio, I need to know why do you need that feature at a global level, because I'm not sure such a functionality is useful, if you have a 2 decimal mask would it fit your need ? You could always divide/multiplicate it by 100 after the input.

**Comment by caio-delgado** [comment]
The thing is the way it works you always need to input leading zeros to reach the end of the mask. When you type in currency leading zeros are insignificant. You don’t want to force leading zeros on your user. That’s where filling from right to left becomes relevant. It’s a feature present/requested in other libraries and language as well:Input Mask Currencycodepen.iohttps://github.com/sanniassin/react-input-mask/issues/120Money question · Issue #644 · RobinHerbots/Inputmaskgithub.comIt’s not just for money too. Any number with insignificant leading zeros and a significant information at the end of the mask could benefit from it. Thanks for replyingCaioEm 9 de dez. de 2023, à(s) 08:54, Raphaël Desalbres ***@***.***> escreveu:﻿
Hello Caio, I need to know why do you need that feature at a global level, because I'm not sure such a functionality is useful, if you have a 2 decimal mask would it fit your need ? You could always divide/multiplicate it by 100 after the input.

**Comment by raphadesa** [comment]
Hi Caio,

Unfortunately it's a too much specific question for me to handle.

Please refer to https://imask.js.org as this is the component BlazorInputMask uses. Their mask plugin has infinite use cases.  If necessary you can open an issue with them, and after include BlazorInputMask in your project and adapt it to fit your need as it's open source.

Regards,

Raphaël

**Comment by caio-delgado** [comment]
Thanks for replying anyway. I ended up managing to use robinherbots library. It has the numeric input setting that does what I need (fill from right to left). Imask doesn’t implement it. CaioEm 10 de dez. de 2023, à(s) 15:57, Raphaël Desalbres ***@***.***> escreveu:﻿
Hi Caio,
Unfortunately it's a too much specific question for me to handle.
Please refer to https://imask.js.org as this is the component BlazorInputMask uses. Their mask plugin has infinite use cases.  If necessary you can open an issue with them, and after include BlazorInputMask in your project and adapt it to fit your need as it's open source.
Regards,
Raphaël
