### ISSUE TITLE
Add configuration for when to update value

### ISSUE THREAD

**Issue by LavenHook** [raphadesa/BlazorInputMask#3]
I'm having a problem, and it even shows up in your demo gif -
When you type a character into an InputMask, that field is automatically validated against Blazor validation  (i.e. the input's change/keyup/keydown event fires in JS and causes a callback to Blazor, where the Edit context picks up a field change, and causes validation to occur). This might be desirable in some circumstances, In my case, though, the field needs to not validate until the input has lost focus.

I'm sure this has to do with the default behavior of the IMask library - but does the library provide a way to customize that behavior? If so, could that behavior also be customized in the InputMask component, or even just by providing a customized window.mask function?

Thanks

**Comment by raphadesa** [comment]
Hello,

First of all thanks for your input...

I have updated the nuget Package and added a new property on the InputMask component, which is called "validateOnKeyPress" which is true by default, so in you case you should set it to false.

Regards,

Raphaël

**Comment by LavenHook** [comment]
Much different solution than I was expecting.

~~I'll test it out as soon as I get a chance.~~
Seems to do the trick! Thanks.

**Comment by raphadesa** [comment]
Hello, I've removed the messing property, tell me if it works for you ! I've updated the NuGet package to .net 5.
