### ISSUE TITLE
Omit JS reference requirement

### ISSUE THREAD

**Issue by Cheeseless** [raphadesa/BlazorInputMask#30]
Would it be possible for this package to be set up in such a way as to allow usage without adding the script references to _Host.cshtml or Index.html? Keeping js as close to completely invisible as possible would be ideal for ease of use.

**Comment by raphadesa** [comment]
Hello,

You could try to embed the javascript in a dll, but I don't know if that would work.

And I don't know if the Blazor team would implement such a functionality.

Regards,

Raphaël
