### ISSUE TITLE
cant work for regular expression containing symbols

### ISSUE THREAD

**Issue by omarceloribeiro** [raphadesa/BlazorInputMask#31]
can't make it work for a regular expression to validate time accepting value from 00:00 to 23:59.
imask native also has this limitation.
iMask requires to use groups:

var maskOptions = {
  mask: 'HH{:}`MM',
  groups: {
    HH: new IMask.MaskedPattern.Group.Range([0, 23]),
    MM: new IMask.MaskedPattern.Group.Range([0, 59])
  }
}

https://github.com/uNmAnNeR/imaskjs/issues/53

**Comment by raphadesa** [comment]
Thanks for that information but I currently don't have plans to update the component with such a funcionality....
