### ISSUE TITLE
IsDisabled property?

### ISSUE THREAD

**Issue by wcmeredith** [raphadesa/BlazorInputMask#4]
Could an IsDisabled property be added to the control?

**Comment by raphadesa** [comment]
Hi William, in fact this feature is already provided by default, simply add a disabled="disabled" attribute or just bind the disabled attribute to a boolean.
Hope this helps !
Raphaël...

**Comment by wcmeredith** [comment]
Thanks! Must have not been paying attention to my poor typing. Good work on this.
