### ISSUE TITLE
Error when using Server Side Blazor

### ISSUE THREAD

**Issue by ryanbuening** [raphadesa/BlazorInputMask#5]
I'm testing using BlazorInputMask on both a server and client Blazor project. My client project is working fine. The server project is throwing this error:

```
Error: Microsoft.JSInterop.JSException: Cannot read property 'isContentEditable' of null
TypeError: Cannot read property 'isContentEditable' of null at new n (https://localhost:5000/_content/BlazorInputMask/IMask.js:1:49179)
```

Below is my custom input component

```
@inject IJSRuntime JSRuntime
@inherits InputBase<string>
@using System.Linq.Expressions

<input @attributes="@AdditionalAttributes" class="form-control @CssClass" @bind="@CurrentValueAsString" @bind:event="oninput" />
<ValidationMessage For="@ValidationFor" />

@code {
	[Parameter] public string Id { get; set; }
	[Parameter] public string Label { get; set; }
	[Parameter] public Expression<Func<string>> ValidationFor { get; set; }
	[Parameter] public ElementReference ElementReference { get; set; }
	[Parameter] public string Mask { get; set; }
	[Parameter] public string RawValue { get; set; }

	protected override void OnInitialized()
	{
		if (string.IsNullOrEmpty(Id))
			Id = Guid.NewGuid().ToString();
	}

	protected override bool TryParseValueFromString(string value, out string result, out string validationErrorMessage)
	{
		result = value;
		validationErrorMessage = null;
		return true;
	}

	protected override async Task OnAfterRenderAsync(bool firstRender)
	{
		if (firstRender && !String.IsNullOrEmpty(Mask))
		{
			await JSRuntime.InvokeVoidAsync("mask", Id, @Mask, DotNetObjectReference.Create(this));
		}
	}

	[JSInvokable]
	public void returnUnmaskedValue(string value)
	{
		RawValue = value;
	}
}
```

and how I use the custom input...

`<CustomInputText @bind-Value="PropertyViewModel.BuildingAmount" ValidationFor="@(() => PropertyViewModel.BuildingAmount)" Mask="00000" />`

Any ideas?

**Comment by raphadesa** [comment]
Hello,

Are you sure you have referenced the proper JS ?

________________________________
De : Ryan Buening <notifications@github.com>
Envoyé : vendredi, décembre 4, 2020 10:22 PM
À : raphadesa/BlazorInputMask
Cc : Subscribed
Objet : [raphadesa/BlazorInputMask] Error when using Server Side Blazor (#5)


I'm testing using BlazorInputMask on both a server and client Blazor project. My client project is working fine. The server project is throwing this error:

Error: Microsoft.JSInterop.JSException: Cannot read property 'isContentEditable' of null
TypeError: Cannot read property 'isContentEditable' of null at new n (https://localhost:5000/_content/BlazorInputMask/IMask.js:1:49179)


Below is my custom input component

@inject IJSRuntime JSRuntime
@inherits InputBase<string>
@using System.Linq.Expressions

<input @attributes="@AdditionalAttributes" class="form-control @CssClass" @bind="@CurrentValueAsString" @bind:event="oninput" />
<ValidationMessage For="@ValidationFor" />

@code {
        [Parameter] public string Id { get; set; }
        [Parameter] public string Label { get; set; }
        [Parameter] public Expression<Func<string>> ValidationFor { get; set; }
        [Parameter] public ElementReference ElementReference { get; set; }
        [Parameter] public string Mask { get; set; }
        [Parameter] public string RawValue { get; set; }

        protected override void OnInitialized()
        {
                if (string.IsNullOrEmpty(Id))
                        Id = Guid.NewGuid().ToString();
        }

        protected override bool TryParseValueFromString(string value, out string result, out string validationErrorMessage)
        {
                result = value;
                validationErrorMessage = null;
                return true;
        }

        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
                if (firstRender && !String.IsNullOrEmpty(Mask))
                {
                        await JSRuntime.InvokeVoidAsync("mask", Id, @Mask, DotNetObjectReference.Create(this));
                }
        }

        [JSInvokable]
        public void returnUnmaskedValue(string value)
        {
                RawValue = value;
        }
}


and how I use the custom input...

<CustomInputText @bind-Value="PropertyViewModel.BuildingAmount" ValidationFor="@(() => PropertyViewModel.BuildingAmount)" Mask="00000" />

Any ideas?

**Comment by ryanbuening** [comment]
In `_Host.cshtml` I have added the following two scripts:

```
<script src="_content/BlazorInputMask/Main.js"></script>
<script src="_content/BlazorInputMask/IMask.js"></script>
```

Is there any other setup I might be missing or something else I need to be referencing?

**Comment by ryanbuening** [comment]
I solved the issue. I didn't have an id on my custom input. Needed to add `id="@Id"` to the `<input />`

`<input id="@Id" @attributes="@AdditionalAttributes" class="form-control @CssClass" @bind="@CurrentValueAsString" @bind:event="oninput" />`
