### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by VahidShir** [raphadesa/BlazorInputMask#6]
If I use InputMask I get this upon entering the page:
`System.NullReferenceException: 'Object reference not set to an instance of an object.'`

Here's what I did:
- Installed the Nuget package
- Added these two lines in _Host.cshtml:
```
<script src="_content/BlazorInputMask/Main.js"></script>
<script src="_content/BlazorInputMask/IMask.js"></script>
```

And here's my page:
```
<InputMask @ref="mask" id="test" @bind-Value="value" class="form-control" data-mask="----------" />

@code{
    private string value;
    InputMask mask { get; set; }
    private bool wasSubmitted { get; set; }
    public string maskedOnly { get; set; }
    private void Submit()
    {
        var rawValue = mask.rawValue;
        wasSubmitted = true;
    }
}
```
_Host.cshtml:
![image](https://user-images.githubusercontent.com/8729558/108672652-b5286680-74f7-11eb-9ef6-228fc21a5fa9.png)

**Comment by raphadesa** [comment]
Hello,

Sorry for the late reply, but I thing you have to put the Blazor script tag at the end of your file. Give it a try and tell me whether this fixes the bug.
Regards,

Raphael

________________________________
De : Vahid Shirmohammadi <notifications@github.com>
Envoyé : Monday, February 22, 2021 7:55:23 AM
À : raphadesa/BlazorInputMask <BlazorInputMask@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [raphadesa/BlazorInputMask] NullReferenceException (#6)


If I use InputMask I get this upon entering the page:
System.NullReferenceException: 'Object reference not set to an instance of an object.'

Here's what I did:

  *   Installed the Nuget package
  *   Added these two lines in _Host.cshtml:

<script src="_content/BlazorInputMask/Main.js"></script>
<script src="_content/BlazorInputMask/IMask.js"></script>


And here's my page:

<InputMask @ref="mask" id="test" @bind-Value="value" class="form-control" data-mask="----------" />

@code{
    private string value;
    InputMask mask { get; set; }
    private bool wasSubmitted { get; set; }
    public string maskedOnly { get; set; }
    private void Submit()
    {
        var rawValue = mask.rawValue;
        wasSubmitted = true;
    }
}


_Host.cshtml:
[image]<https://user-images.githubusercontent.com/8729558/108672652-b5286680-74f7-11eb-9ef6-228fc21a5fa9.png>

**Comment by raphadesa** [comment]
Hi Vahid,

You should use an EditForm to use the component, you can't bind a value to a variable directly.

You can see an example here :

BlazorInputMask/Pages/Index.razor

Regards,

Raphaël

**Comment by VahidShir** [comment]
Hi @raphadesa 

I had already used the component in an EditForm, just similar to that example. I put only that single line for brevity.

**Comment by FreddieMiles** [comment]
I was having the same issue and corrected it by looking at @raphadesa 's code and creating my own razor masking component using @raphadesa's codebase. Once you get this done, everything works. You will have to name your razor component anything other than InputMask.

**Comment by raphadesa** [comment]
Hello, sorry for the late reply, but I've been busy with my kids ;) !
I created a new project and followed the steps of @VahidShir, but I wasn't enable to reproduce the error. Are you sure your mask is valid? 
In the meantime I've upgraded the NuGet package with the latest .NET 5 SDK. Hope this helps  !
