### ISSUE TITLE
Missing Main.js file

### ISSUE THREAD

**Issue by zabanet** [raphadesa/BlazorInputMask#7]
It looks like the **Main.js** file is missing in the nugget package. I can see **IMask.js** in Chrome developer console but not **Main.js**. I suppose that this is the reason of my error: 

>  Error: Microsoft.JSInterop.JSException: Could not find 'mask' ('mask' was undefined). 
>  Error: Could not find 'mask' ('mask' was undefined).

When I copied the file from the GitHub project, everything worked like charm.

**Comment by clsyan0** [comment]
I was getting this error. First i tried to just install and call InputMask component, but it did not work. Then, i tried to copy all the code and create the files manually, it did not work either. What worked  for me was create all the files manually, insert the script tags and the scripts (as shown in the README) in the index html file, then name my InputMask component anything but "InputMask".

**Comment by raphadesa** [comment]
Hello, did you try to add that in your _Host.cshtml or Index.html file ? 

<script src="_content/BlazorInputMask/Main.js"></script>
<script src="_content/BlazorInputMask/IMask.js"></script>
