### ISSUE TITLE
How to pass regular expression?

### ISSUE THREAD

**Issue by shalinparmar** [raphadesa/BlazorInputMask#8]
How do we pass regular expressions for data-mask? I see that IMask.js supports it but hard to pass from BlazorInputMask component?

**Comment by raphadesa** [comment]
Hello, you maybe can try to assign the regular expression to a string variable, and bind that string to the component.

**Comment by shalinparmar** [comment]
@raphadesa doesn't seem to work with data-mask attribute.

**Comment by raphadesa** [comment]
Hello @shalinparmar 

Sorry for the delay !

RegEx is now supported on version 1.0.8 !

You shoud use : (RegEx must start and end with a slash '/')

<InputMask @ref="mask" id="test" @bind-Value="user.Telephone" class="form-control" data-mask="/^\d+$/"  placeholder="Phone No"  />

I've also updated the Nuget Package.

Hope this helps !

Raphaël
