### ISSUE TITLE
deprecated ValidateOnKeyPress Question 

### ISSUE THREAD

**Issue by LavenHook** [raphadesa/BlazorInputMask#9]
Why did you deprecate the ValidateOnKeyPress flag?

Is there a preferred way to ensure that validation is not performed with every keystroke?

Thanks,

**Comment by raphadesa** [comment]
Hello Isaac,

Basically what you shoud do is use the EditContext, and bind to the OnFieldChange event.

I've added a sample here : BlazorInputMask/Pages/Index2.razor

Hope this helps,

Raphaël

**Comment by LavenHook** [comment]
Thanks for that information and the example.

I'm using InputMask under slightly more convoluted circumstances.
1. In many cases I already have an event that is used to determine when validation should be done. I have to do it this way because there are multiple sections within a form sometimes. That causes me to have to juggle several FieldIdentifiers throughout any given form. 
2. In many places, I am dealing with nested objects - especially where the user may be maintaining a list of something, where the form for each entry uses an InputMask. This would be much easier to handle at the sub-component level.

There is, unfortunately, no way around the first point, at least the way the code is that I'm working with. The second point _was_ mitigated by setting the ValidateOnKeyPress. I'm not sure I see a reasonably maintainable way to combine a solution for the second point into what I have for the first - the logic for each even will get compounded by each InputMask. 

I thought that your previous implementation for ValidateOnKeyPress was pretty slick. It allowed me to manage the validation at the sub-component level.

As I'm typing this out - it occurs to me that I _may_ be able to use `@bind:event`. I think I had tried that with one of the previous versions, but it didn't work because InputMask explicitly invoked validation. Since that's no longer the case, that might be another possible approach now.

Once again, thanks for your work on this project.

**Comment by raphadesa** [comment]
Hello, 

I've updated the documentation and NuGet package to add validateOnKeyPress which is true by default.

Hope this helps,

Raphaël
